ConfigException: Add the ability to format a path/key
Currently, all the formatting is done manually at the call site.
If we want to make colors optional and simplify the output,
it needs to be moved inside the Exception itself.