ConfigException: Extend 'toString' to accept a FormatSpec
This way we can choose whether colors are used or not,
which might be required when the output is not a TTY.